# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tongust/Projects/sbwt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tongust/Projects/sbwt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tongust/Projects/sbwt/CMakeFiles /home/tongust/Projects/sbwt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tongust/Projects/sbwt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named count_occ

# Build rule for target.
count_occ: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 count_occ
.PHONY : count_occ

# fast build rule for target.
count_occ/fast:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/build
.PHONY : count_occ/fast

#=============================================================================
# Target rules for targets named build_index

# Build rule for target.
build_index: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 build_index
.PHONY : build_index

# fast build rule for target.
build_index/fast:
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/build
.PHONY : build_index/fast

alphabet.o: alphabet.c.o

.PHONY : alphabet.o

# target to build an object file
alphabet.c.o:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/alphabet.c.o
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/alphabet.c.o
.PHONY : alphabet.c.o

alphabet.i: alphabet.c.i

.PHONY : alphabet.i

# target to preprocess a source file
alphabet.c.i:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/alphabet.c.i
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/alphabet.c.i
.PHONY : alphabet.c.i

alphabet.s: alphabet.c.s

.PHONY : alphabet.s

# target to generate assembly for a file
alphabet.c.s:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/alphabet.c.s
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/alphabet.c.s
.PHONY : alphabet.c.s

build_index.o: build_index.cc.o

.PHONY : build_index.o

# target to build an object file
build_index.cc.o:
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/build_index.cc.o
.PHONY : build_index.cc.o

build_index.i: build_index.cc.i

.PHONY : build_index.i

# target to preprocess a source file
build_index.cc.i:
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/build_index.cc.i
.PHONY : build_index.cc.i

build_index.s: build_index.cc.s

.PHONY : build_index.s

# target to generate assembly for a file
build_index.cc.s:
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/build_index.cc.s
.PHONY : build_index.cc.s

count_occ.o: count_occ.cc.o

.PHONY : count_occ.o

# target to build an object file
count_occ.cc.o:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/count_occ.cc.o
.PHONY : count_occ.cc.o

count_occ.i: count_occ.cc.i

.PHONY : count_occ.i

# target to preprocess a source file
count_occ.cc.i:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/count_occ.cc.i
.PHONY : count_occ.cc.i

count_occ.s: count_occ.cc.s

.PHONY : count_occ.s

# target to generate assembly for a file
count_occ.cc.s:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/count_occ.cc.s
.PHONY : count_occ.cc.s

log.o: log.cc.o

.PHONY : log.o

# target to build an object file
log.cc.o:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/log.cc.o
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/log.cc.o
.PHONY : log.cc.o

log.i: log.cc.i

.PHONY : log.i

# target to preprocess a source file
log.cc.i:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/log.cc.i
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/log.cc.i
.PHONY : log.cc.i

log.s: log.cc.s

.PHONY : log.s

# target to generate assembly for a file
log.cc.s:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/log.cc.s
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/log.cc.s
.PHONY : log.cc.s

ref_read.o: ref_read.cpp.o

.PHONY : ref_read.o

# target to build an object file
ref_read.cpp.o:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/ref_read.cpp.o
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/ref_read.cpp.o
.PHONY : ref_read.cpp.o

ref_read.i: ref_read.cpp.i

.PHONY : ref_read.i

# target to preprocess a source file
ref_read.cpp.i:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/ref_read.cpp.i
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/ref_read.cpp.i
.PHONY : ref_read.cpp.i

ref_read.s: ref_read.cpp.s

.PHONY : ref_read.s

# target to generate assembly for a file
ref_read.cpp.s:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/ref_read.cpp.s
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/ref_read.cpp.s
.PHONY : ref_read.cpp.s

sbwt.o: sbwt.cc.o

.PHONY : sbwt.o

# target to build an object file
sbwt.cc.o:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/sbwt.cc.o
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/sbwt.cc.o
.PHONY : sbwt.cc.o

sbwt.i: sbwt.cc.i

.PHONY : sbwt.i

# target to preprocess a source file
sbwt.cc.i:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/sbwt.cc.i
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/sbwt.cc.i
.PHONY : sbwt.cc.i

sbwt.s: sbwt.cc.s

.PHONY : sbwt.s

# target to generate assembly for a file
sbwt.cc.s:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/sbwt.cc.s
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/sbwt.cc.s
.PHONY : sbwt.cc.s

utility.o: utility.cc.o

.PHONY : utility.o

# target to build an object file
utility.cc.o:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/utility.cc.o
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/utility.cc.o
.PHONY : utility.cc.o

utility.i: utility.cc.i

.PHONY : utility.i

# target to preprocess a source file
utility.cc.i:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/utility.cc.i
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/utility.cc.i
.PHONY : utility.cc.i

utility.s: utility.cc.s

.PHONY : utility.s

# target to generate assembly for a file
utility.cc.s:
	$(MAKE) -f CMakeFiles/count_occ.dir/build.make CMakeFiles/count_occ.dir/utility.cc.s
	$(MAKE) -f CMakeFiles/build_index.dir/build.make CMakeFiles/build_index.dir/utility.cc.s
.PHONY : utility.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... count_occ"
	@echo "... build_index"
	@echo "... alphabet.o"
	@echo "... alphabet.i"
	@echo "... alphabet.s"
	@echo "... build_index.o"
	@echo "... build_index.i"
	@echo "... build_index.s"
	@echo "... count_occ.o"
	@echo "... count_occ.i"
	@echo "... count_occ.s"
	@echo "... log.o"
	@echo "... log.i"
	@echo "... log.s"
	@echo "... ref_read.o"
	@echo "... ref_read.i"
	@echo "... ref_read.s"
	@echo "... sbwt.o"
	@echo "... sbwt.i"
	@echo "... sbwt.s"
	@echo "... utility.o"
	@echo "... utility.i"
	@echo "... utility.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

